services:
  wallets.database:
    image: postgres:15-alpine
    container_name: wallets.database
    environment:
        - POSTGRES_DB=wallets
        - POSTGRES_USER=dev
        - POSTGRES_PASSWORD=dev
    volumes:
        - ./_scripts/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:rw
    ports:
        - 5432:5432
