
POST  http://localhost:5014/v1/wallets
Accept: text/plain
Content-Type: application/json

{
  "accountHolderModel": {
    "name": "string",
    "taxId": "string"
  },
  "accountModel": {
    "number": "string",
    "branch": "string"
  }
}
###
